# Header

menu:
  Home: /
  Articles: /tags/articles/

# SubNav
subnav:
  github: "#"
  rss: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml


#  If your website is stored in a subdirectory, such as http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# The article is too long, cut off the button text
excerpt_link: more
# #Article card in the lower right corner of the resident link, do not need to set to false
show_all_link: 'Next'
# Math formula
mathjax: false
# # Whether to open the link in a new window
open_in_new: false

# Setting: 0-off reward; 1-review: true attribute in the md file corresponding to the article, only rewards;
# 2- all articles have rewards
reward_type: 2
# Reward wording
reward_wording: 'Thanks'
#Alipay QR code image address, the same way you set the avatar. such as ：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#url
avatar:

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# Style customization - generally do not need to be modified unless there is a strong desire to customize...
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 'All articles'
  friends: 'Friends'
  aboutme: 'About'

friends:
  Links 1: http://localhost:4000/
  Links 2: http://localhost:4000/
  Links 3: http://localhost:4000/
  Links 4: http://localhost:4000/
  Links 5: http://localhost:4000/
  Links 6: http://localhost:4000/

aboutme: Product Designer<br><br>Technology Dies Around Me<br>
